apiVersion: v1
kind: Service
metadata:
  name: his-registration
  namespace: his-registration
spec:
  type: ClusterIP
  selector:
    app: his-registration
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
